[workspace]
resolver = "2"
members = ["crates/epw", "crates/epw-py", "crates/epw-ex/native/epw_ex"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.metadata.crane]
name = "epw-workspace"

[profile.release]
lto = "thin"
