[bans]
multiple-versions = "allow"

[licenses]
private = { ignore = true }
allow = [
  "Apache-2.0 WITH LLVM-exception",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSL-1.0",
  "ISC",
  "MIT",
  "Unicode-3.0",
  "Zlib",
]
