[package]
name = "epw-py"
version.workspace = true
edition.workspace = true
license = "MIT"

[lib]
name = "epw"
crate-type = ["cdylib"]
test = false
doctest = false

[dependencies]
epw = { version = "0.1.0", path = "../epw" }
pyo3 = { version = "0.24.1", features = ["chrono", "extension-module"] }
