name: build

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/dependabot.yml"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform:
          - arm64
          - amd64

    permissions:
      id-token: write
      contents: read

    runs-on: ["arc-runner-small-${{ matrix.platform }}"]

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/cachix-action@v15
        with:
          name: nablaflow
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
        env:
          USER: runner

      - run: nix flake check -L
